spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  jms:
    pub-sub-domain: false
  activemq:
    user: admin    # 连接用户名
    password: admin   # 连接密码
    broker-url: tcp://localhost:61616 # 消息组件的连接主机信息